### PR TITLE
Develop branch refactoring.

### PR DESCRIPTION
**Pull request by cron1155**
This PR adds new `LOGGER Macros` and refactors old features making easier to add new features.
A lot of libraries were moved from the `include` directory to their own directory.
It also removes F4MPReverse/Common because it was useless.

### CODE REVIEW

**Comment by 0rdinal** [comment]
I don't know why you closed this. I was more than happy to review this once I woke up.

**Comment by cron1155** [comment]
> 
> 
> I don't know why you closed this. I was more than happy to review this once I woke up.

Don't worry. There are some problems with the cmake files. Going to change them and reopen the PR

**Comment by 0rdinal** [comment]
Seeing that this is the develop version and most of these commits are dependency and not feature related. I'm going to permit merging without a review. You're still welcome to join the discord if you want. 

Respond to this message that your happy for the code to be merged and I will merge it.

**Comment by cron1155** [comment]
> 
> 
> Seeing that this is the develop version and most of these commits are dependency and not feature related. I'm going to permit merging without a review. You're still welcome to join the discord if you want.
> 
> Respond to this message that your happy for the code to be merged and I will merge it.

I'm already on the discord server and you can merge it.

**Pull request merged**
